repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks 
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: "Add license header (Python)"
        args:
          - --license-filepath=LICENSE-HEADER.txt
          - --comment-style=#
          - --use-current-year
          - --detect-license-in-X-top-lines=10
        types: [python]

  - repo: https://github.com/astral-sh/ruff-pre-commit 
    rev: v0.14.11
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
